.TH SIMEIS 1 "DATE" "VERSION" "Simeis Manual"
.\" Manpage for simeis.
.SH NAME
simeis \- jeu par API
.SH SYNOPSIS
simeis-server
.SH DESCRIPTION
Simeis est un jeu par API (inspiré de SpaceTraders), dont le but est de faire fructifier votre
empire économique dans toute la galaxie
.SH BUGS
No known bugs.
.SH AUTHOR
CHAFFAUX Kevin (kevin.chaffaux@ynov.com)
FERRON Evan (ferron.evan@ynov.com)
BIGOT Lucas (lucas.bigot@ynov.com)
