name: "CI - Main"

env:
  CARGO_TERM_COLOR: always

on:
  pull_request:
    branches:
      - "main"

jobs:
  quality:
    name: Quality
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v6

      - name: Installation de rust
        run: make rust-init

      - name: Formatage
        run: make rust-fmt

      - name: Linting
        run: make rust-lint

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v6

      - name: Installation de rust
        run: make rust-init

      - name: Lancement des tests
        run: make rust-test

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v6

      - name: Installation de rust
        run: make rust-init

      - name: Compilation du projet
        run: make rust-build

      - name: Création de la documentation typst
        run: |
          make rust-docu
