name: Ci Release

on:
  pull_request:
    branches:
      - "release/*"

jobs:
  origin: # Origin fait échouer la pr afin de montrer au dev qu'il s'est trompé d'origine
    name: Vérification de l'origine de la release
    runs-on: ubuntu-latest
    steps:
      - name: Échoue si l'origine de PR n'est pas valide
        run: |
          SOURCE_REF="${{ github.head_ref }}"
          if [[ "$SOURCE_REF" != "main" && ! "$SOURCE_REF" =~ ^bug/ ]]; then
            exit 1
          fi

  setup-py:
    needs: origin
    name: Setup PYTHON
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v6

      - name: Python cache
        uses: ./.github/actions/python-cache
        with:
          main-cache-version: ${{ vars.MAIN_CACHE_VERSION }}
          python-init-cache-version: ${{ vars.PYTHON_INIT_CACHE_VERSION }}

  setup-rust:
    needs: origin
    name: Setup RUST
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code # Nécessaire pour récupérer le action.yml
        uses: actions/checkout@v6

      - name: Rust cache + build
        uses: ./.github/actions/rust-cache
        with:
          main-cache-version: ${{ vars.MAIN_CACHE_VERSION }}
          rust-init-cache-version: ${{ vars.RUST_INIT_CACHE_VERSION }}
          rust-build-cache-version: ${{ vars.RUST_BUILD_CACHE_VERSION }}

  quality:
    name: Quality
    needs: setup-rust
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v6

      - name: Rust cache + build
        uses: ./.github/actions/rust-cache
        with:
          main-cache-version: ${{ vars.MAIN_CACHE_VERSION }}
          rust-init-cache-version: ${{ vars.RUST_INIT_CACHE_VERSION }}
          rust-build-cache-version: ${{ vars.RUST_BUILD_CACHE_VERSION }}

      - name: Python cache
        uses: ./.github/actions/python-cache
        with:
          main-cache-version: ${{ vars.MAIN_CACHE_VERSION }}
          python-init-cache-version: ${{ vars.PYTHON_INIT_CACHE_VERSION }}

      - name: Formatage
        run: make fmt

      - name: Linting
        run: make lint

      - name: Audit
        run: make rust-audit

      - name: Udeps
        run: make rust-udeps

  tests:
    name: Tests
    needs: setup-rust
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v6

      - name: Rust cache + build
        uses: ./.github/actions/rust-cache
        with:
          main-cache-version: ${{ vars.MAIN_CACHE_VERSION }}
          rust-init-cache-version: ${{ vars.RUST_INIT_CACHE_VERSION }}
          rust-build-cache-version: ${{ vars.RUST_BUILD_CACHE_VERSION }}

      - name: Python cache
        uses: ./.github/actions/python-cache
        with:
          main-cache-version: ${{ vars.MAIN_CACHE_VERSION }}
          python-init-cache-version: ${{ vars.PYTHON_INIT_CACHE_VERSION }}

      - name: Lancement des tests
        run: make rust-test-release

      - name: Lancement des tests avec heavy-testing
        run: make rust-heavy-test

  python-property-test-heavy:
    name: Tests property-based (lourd)
    needs: [setup-rust, setup-py]
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v6

      - name: Rust cache + build
        uses: ./.github/actions/rust-cache
        with:
          main-cache-version: ${{ vars.MAIN_CACHE_VERSION }}
          rust-init-cache-version: ${{ vars.RUST_INIT_CACHE_VERSION }}
          rust-build-cache-version: ${{ vars.RUST_BUILD_CACHE_VERSION }}

      - name: Python cache
        uses: ./.github/actions/python-cache
        with:
          main-cache-version: ${{ vars.MAIN_CACHE_VERSION }}
          python-init-cache-version: ${{ vars.PYTHON_INIT_CACHE_VERSION }}

      - name: Tests property-based (mode lourd)
        run: make python-property-test-heavy

  python-functional-test:
    name: Tests functionnal
    needs: [setup-rust, setup-py]
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v6

      - name: Rust cache + build
        uses: ./.github/actions/rust-cache
        with:
          main-cache-version: ${{ vars.MAIN_CACHE_VERSION }}
          rust-init-cache-version: ${{ vars.RUST_INIT_CACHE_VERSION }}
          rust-build-cache-version: ${{ vars.RUST_BUILD_CACHE_VERSION }}

      - name: Python cache
        uses: ./.github/actions/python-cache
        with:
          main-cache-version: ${{ vars.MAIN_CACHE_VERSION }}
          python-init-cache-version: ${{ vars.PYTHON_INIT_CACHE_VERSION }}

      - name: Tests functionnal
        run: make python-functional-test

  build:
    name: Build
    needs: [quality, tests, python-property-test-heavy, python-functional-test]
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v6

      - name: Rust cache + build
        uses: ./.github/actions/rust-cache
        with:
          main-cache-version: ${{ vars.MAIN_CACHE_VERSION }}
          rust-init-cache-version: ${{ vars.RUST_INIT_CACHE_VERSION }}
          rust-build-cache-version: ${{ vars.RUST_BUILD_CACHE_VERSION }}

      - name: Compilation
        run: make rust-build-release

      - name: Optimisation executable
        run: |
          ls -lah ./target/release/
          strip ./target/release/simeis-server
          ls -lah ./target/release/
