name: Ci Release

on:
  pull_request:
    branches:
      - "release/*"

jobs:
  origin: # Origin fait échouer la pr afin de montrer au dev qu'il s'est trompé d'origine
    name: Vérification de l'origine de la release
    runs-on: ubuntu-latest
    steps:
      - name: Échoue si l'origine de PR n'est pas valide
        run: |
          SOURCE_REF="${{ github.head_ref }}"
          if [[ "$SOURCE_REF" != "main" && ! "$SOURCE_REF" =~ ^bug/ ]]; then
            exit 1
          fi

  setup-py:
    name: Setup PYTHON
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v6

      - name: Cache python install
        id: cache-python
        uses: actions/cache@v4
        env:
          cache-name: cache-init
        with:
          path: |
            ./test_env/
          key: ${{ runner.os }}-python-${{ env.cache-name }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-python-${{ env.cache-name }}-
            ${{ runner.os }}-python-
            ${{ runner.os }}-

      - if: ${{ steps.cache-python.outputs.cache-hit != 'true' }}
        name: Installation de python
        run: make python-init

  setup-rust:
    name: Setup RUST
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v6

      - name: Cache rust install
        id: cache-rust
        uses: actions/cache@v4
        env:
          cache-name: cache-init
        with:
          path: |
            ./target/
            ~/.cargo
          key: ${{ runner.os }}-rust-${{ env.cache-name }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-rust-${{ env.cache-name }}-
            ${{ runner.os }}-rust-
            ${{ runner.os }}-

      - if: ${{ steps.cache-rust.outputs.cache-hit != 'true' }}
        name: Installation de rust
        run: make rust-init

  quality:
    name: Quality
    needs: setup-rust
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v6

      - name: Cache rust install
        id: cache-rust
        uses: actions/cache/restore@v4
        env:
          cache-name: cache-init
        with:
          path: |
            ./target/
            ~/.cargo
          key: ${{ runner.os }}-rust-${{ env.cache-name }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-rust-${{ env.cache-name }}-
            ${{ runner.os }}-rust-
            ${{ runner.os }}-

      - name: Formatage
        run: make fmt

      - name: Linting
        run: make lint

      - name: Audit
        run: make rust-audit

      - name: Udeps
        run: make udeps

  tests:
    name: Tests
    needs: setup-rust
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v6

      - name: Cache rust install
        id: cache-rust
        uses: actions/cache/restore@v4
        env:
          cache-name: cache-init
        with:
          path: |
            ./target/
            ~/.cargo
          key: ${{ runner.os }}-rust-${{ env.cache-name }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-rust-${{ env.cache-name }}-
            ${{ runner.os }}-rust-
            ${{ runner.os }}-

      - name: Lancement des tests
        run: make rust-test-release

      - name: Lancement des tests avec heavy-testing
        run: make test-heavy-testing

  python-property-test-heavy:
    name: Tests property-based (lourd)
    needs: [setup-rust, setup-py]
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v6

      - name: Cache rust install
        id: cache-rust
        uses: actions/cache/restore@v4
        env:
          cache-name: cache-init
        with:
          path: |
            ./target/
            ~/.cargo
          key: ${{ runner.os }}-rust-${{ env.cache-name }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-rust-${{ env.cache-name }}-
            ${{ runner.os }}-rust-
            ${{ runner.os }}-

      - name: Cache python
        id: cache-python
        uses: actions/cache/restore@v4
        env:
          cache-name: cache-init
        with:
          path: |
            ./test_env/
          key: ${{ runner.os }}-python-${{ env.cache-name }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-python-${{ env.cache-name }}-
            ${{ runner.os }}-python-
            ${{ runner.os }}-

      - name: Tests property-based (mode lourd)
        run: make python-property-test-heavy

  python-functional-test:
    name: Tests functionnal
    needs: [setup-rust, setup-py]
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v6

      - name: Cache rust install
        id: cache-rust
        uses: actions/cache/restore@v4
        env:
          cache-name: cache-init
        with:
          path: |
            ./target/
            ~/.cargo
          key: ${{ runner.os }}-rust-${{ env.cache-name }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-rust-${{ env.cache-name }}-
            ${{ runner.os }}-rust-
            ${{ runner.os }}-

      - name: Cache python
        id: cache-python
        uses: actions/cache/restore@v4
        env:
          cache-name: cache-init
        with:
          path: |
            ./test_env/
          key: ${{ runner.os }}-python-${{ env.cache-name }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-python-${{ env.cache-name }}-
            ${{ runner.os }}-python-
            ${{ runner.os }}-

      - name: Tests functionnal
        run: make python-functional-test

  build:
    name: Build
    needs: [quality, tests, python-property-test-heavy, python-functional-test]
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v6

      - name: Cache rust install
        id: cache-rust
        uses: actions/cache/restore@v4
        env:
          cache-name: cache-init
        with:
          path: |
            ./target/
            ~/.cargo
          key: ${{ runner.os }}-rust-${{ env.cache-name }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-rust-${{ env.cache-name }}-
            ${{ runner.os }}-rust-
            ${{ runner.os }}-

      - name: Compilation
        run: make build-release

      - name: Optimisation executable
        run: |
          ls -lah ./target/release/
          strip ./target/release/simeis-server
          ls -lah ./target/release/
