name: Ci Release

on:
  pull_request:
    branches:
      - "release/*"

jobs:
  origin:
    name: Vérification de l'origine de la release
    runs-on: ubuntu-latest
    # if: ${{ github.repository == 'octo-org/octo-repo-prod' }}
    steps:
      - name: Échoue si la PR ne vient pas de main OU bug/x
        run: |
          echo ${GITHUB_REF}
          echo ${GITHUB_HEAD_REF}

  quality:
    name: Quality
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v6

      - name: Installation de rust
        run: make init

      - name: Formatage
        run: make fmt

      - name: Linting
        run: make lint

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v6

      - name: Installation de rust
        run: make init

      - name: Lancement des tests
        run: make test-release

  build:
    name: Build
    needs: [quality, tests]
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v6

      - name: Installation de rust
        run: make init

      - name: Compilation
        run: make build-release

      - name: Optimisation executable
        run: |
          ls -lah ./target/release/
          strip ./target/release/simeis-server
          ls -lah ./target/release/
