name: "CI"

env:
  CARGO_TERM_COLOR: always

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v6
      - name: Installation de rust
        run: make init
      - name: Compilation
        run: make build
      - name: Lancement
        run: make run
