name: "CI"

env:
  CARGO_TERM_COLOR: always

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v6

      - name: Installation de rust
        run: make init

      - name: Compilation du projet
        run: make build

      - name: Optimisation executable
        run: | # Penser à changer le fichier /debug/ si build avec --release
          ls -lah ./target/debug/
          strip ./target/debug/simeis-server
          ls -lah ./target/debug/

      - name: Mise à jour de la doc
        run: typst compile ./doc/manual.typ ./doc.pdf
