name: Ci Release

on:
    push:
        tags: ["*"]
        branches-ignore: ["*"]

jobs:
    quality:
        name: Quality
        runs-on: ubuntu-latest
        steps:
            - name: Récupération du code
              uses: actions/checkout@v6

            - name: Installation de rust
              run: make init

            - name: Formatage
              run: make fmt

            - name: Linting
              run: make lint
    
    tests:
        name: Tests
        runs-on: ubuntu-latest
        steps:
            - name: Récupération du code
              uses: actions/checkout@v6

            - name: Installation de rust
              run: make init

            - name: Lancement des tests
              run: make test-release

    build:
        name: Build
        needs: [quality, tests]
        runs-on: ubuntu-latest
        steps:
            - name: Récupération du code
              uses: actions/checkout@v6

            - name: Installation de rust
              run: make init

            - name: Compilation
              run: make build-release

            - name: Optimisation executable
              run: |
                  ls -lah ./target/release/
                  strip ./target/release/simeis-server
                  ls -lah ./target/release/
