name: Ci Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  quality:
    name: Quality
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v6

      - name: Installation de rust
        run: make rust-init

      - name: Formatage
        run: make rust-fmt

      - name: Linting
        run: make rust-lint

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v6

      - name: Installation de rust
        run: make rust-init

      - name: Lancement des tests
        run: make rust-test-release

  build:
    name: Build
    needs: [quality, tests]
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v6

      - name: Installation de rust
        run: make rust-init

      - name: Compilation
        run: make rust-build-release

      - name: Optimisation executable
        run: |
          ls -lah ./target/release/
          strip ./target/release/simeis-server
          ls -lah ./target/release/
