name: CI - Quality

env:
  CARGO_TERM_COLOR: always

on:
  pull_request:
    branches:
      - "*"

jobs:
  rust-quality:
    name: Rust quality
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v6

      - name: Installation de rust
        run: make rust-init

      - name: Formatage
        run: make rust-fmt

      - name: Linting
        run: make rust-lint

  python-quality:
    name: Python quality
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v6

      - name: Installation de python
        run: make python-init

      - name: Formatage python
        run: make python-fmt

      - name: Linting python
        run: make python-lint
