name: CI - Quality

env:
  CARGO_TERM_COLOR: always

on:
  pull_request:
    branches:
      - "*"

jobs:
  setup-py:
    name: Setup PYTHON
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v6

      - name: Cache python install
        id: cache-python
        uses: actions/cache@v4
        env:
          cache-name: cache-init
        with:
          path: |
            ./test_env/
          key: ${{ runner.os }}-python-${{ env.cache-name }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-python-${{ env.cache-name }}-
            ${{ runner.os }}-python-
            ${{ runner.os }}-

      - if: ${{ steps.cache-python.outputs.cache-hit != 'true' }}
        name: Installation de python
        run: make python-init

  setup-rust:
    name: Setup RUST
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v6

      - name: Cache rust install
        id: cache-rust
        uses: actions/cache@v4
        env:
          cache-name: cache-init
        with:
          path: |
            ./target/
            ~/.cargo
          key: ${{ runner.os }}-rust-${{ env.cache-name }}-${{ hashFiles('Cargo.lock', 'Makefile') }}
          restore-keys: |
            ${{ runner.os }}-rust-${{ env.cache-name }}-
            ${{ runner.os }}-rust-
            ${{ runner.os }}-

      - if: ${{ steps.cache-rust.outputs.cache-hit != 'true' }}
        name: Installation de rust
        run: |
          make rust-init
          make rust-build

  rust-quality:
    name: Rust quality
    runs-on: ubuntu-latest
    needs: setup-rust
    steps:
      - name: Récupération du code
        uses: actions/checkout@v6

      - name: Cache rust install
        id: cache-rust
        uses: actions/cache/restore@v4
        env:
          cache-name: cache-init
        with:
          path: |
            ./target/
            ~/.cargo
          key: ${{ runner.os }}-rust-${{ env.cache-name }}-${{ hashFiles('Cargo.lock', 'Makefile') }}
          restore-keys: |
            ${{ runner.os }}-rust-${{ env.cache-name }}-
            ${{ runner.os }}-rust-
            ${{ runner.os }}-

      - name: Formatage
        run: make rust-fmt

      - name: Linting
        run: make rust-lint

  python-quality:
    name: Python quality
    runs-on: ubuntu-latest
    needs: setup-py
    steps:
      - name: Récupération du code
        uses: actions/checkout@v6

      - name: Cache python install
        id: cache-python
        uses: actions/cache/restore@v4
        env:
          cache-name: cache-init
        with:
          path: |
            ./test_env/
          key: ${{ runner.os }}-python-${{ env.cache-name }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-python-${{ env.cache-name }}-
            ${{ runner.os }}-python-
            ${{ runner.os }}-

      - name: Formatage python
        run: make python-fmt

      - name: Linting python
        run: make python-lint

  python-property-test:
    name: Tests property-based
    runs-on: ubuntu-latest
    needs: setup-py
    concurrency:
      group: property-test-${{ github.event.pull_request.number }}
      cancel-in-progress: true
    steps:
      - name: Récupération du code
        uses: actions/checkout@v6

      - name: Cache python install
        id: cache-python
        uses: actions/cache/restore@v4
        env:
          cache-name: cache-init
        with:
          path: |
            ./test_env/
          key: ${{ runner.os }}-python-${{ env.cache-name }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-python-${{ env.cache-name }}-
            ${{ runner.os }}-python-
            ${{ runner.os }}-

      - name: Tests property-based
        run: make python-property-test

  python-functional-test:
    name: Tests functionnal
    needs: [setup-rust, python-property-test]
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v6

      - name: Cache rust install
        id: cache-rust
        uses: actions/cache/restore@v4
        env:
          cache-name: cache-init
        with:
          path: |
            ./target/
            ~/.cargo
          key: ${{ runner.os }}-rust-${{ env.cache-name }}-${{ hashFiles('Cargo.lock', 'Makefile') }}
          restore-keys: |
            ${{ runner.os }}-rust-${{ env.cache-name }}-
            ${{ runner.os }}-rust-
            ${{ runner.os }}-

      - name: Cache python install
        id: cache-python
        uses: actions/cache/restore@v4
        env:
          cache-name: cache-init
        with:
          path: |
            ./test_env/
          key: ${{ runner.os }}-python-${{ env.cache-name }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-python-${{ env.cache-name }}-
            ${{ runner.os }}-python-
            ${{ runner.os }}-

      - name: Tests functionnal
        run: make python-functional-test

  tests-coverage:
    name: Vérification couverture de tests
    runs-on: ubuntu-latest
    needs: setup-rust
    permissions:
      contents: read
      pull-requests: write
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Récupération du code
        uses: actions/checkout@v6

      - name: Cache rust install
        id: cache-rust
        uses: actions/cache/restore@v4
        env:
          cache-name: cache-init
        with:
          path: |
            ./target/
            ~/.cargo
          key: ${{ runner.os }}-rust-${{ env.cache-name }}-${{ hashFiles('Cargo.lock', 'Makefile') }}
          restore-keys: |
            ${{ runner.os }}-rust-${{ env.cache-name }}-
            ${{ runner.os }}-rust-
            ${{ runner.os }}-

      - name: Vérification du coverage
        run: |
          # Lancement du coverage (échoue si inférieur à MIN_COVERAGE & sortie json)
          make test-coverage-ci

          # Récupération du chiffre de coverage
          COVERAGE=$(jq '.coverage' tarpaulin-report.json)

          # Si le coverage n'a pas échoué mais qu'il est inférieur à 50% attribution du label "not enough tests"
          if [ $(echo "$COVERAGE < 50.0" | bc) -eq 1 ] 
          then 
            gh pr edit ${{ github.event.number }} --add-label "not enough tests"
          fi
